version: '3.7'
services:
  database:
    image: mysql:5.7
    container_name: mysql_container
    environment:
    - MYSQL_ROOT_PASSWORD=root 
    - MYSQL_DATABASE=flask-db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: bind
      source: ./db/CreateTable.sql
      target: /docker-entrypoint-initdb.d/CreateTable.sql
    
  flask-app:
    build: ./flask-app
    container_name: flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
